version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=canauser
      - APP_USER_PASSWORD=canapass
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "/opt/oracle/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  oracle-data:
    driver: local 